name: flutter_base
description: A base set of UI classes for a consistent look-and-feel across Flutter apps.
version: 0.0.12
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # add this
    sdk: flutter
    version: ^0.0.0

  android_intent_plus: ^4.0.3
  auto_size_text: ^3.0.0
  #bitsdojo_window: ^0.1.5
  bloc_concurrency: ^0.2.4
  collection: ^1.17.0
  data_table_2: ^2.3.10
  dio: ^5.4.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.26.0
  flip_card: ^0.7.0
  floating_action_bubble: ^1.1.4
  flutter_acrylic: ^1.0.0+2
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.4
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.7
  flutter_wizard: ^2.0.5
  json_annotation: ^4.8.1
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4
  get_storage:
  go_router: ^13.2.0
  hive: ^2.2.3
  http: ^1.2.0
  http_query_string: ^1.0.0
  #i18n_extension: ^11.0.12
  loading_indicator: ^3.0.2
  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: d3779be7d661481cc0d99090d6356a286ae4f86b
      path: modal_bottom_sheet
  package_info_plus: ^5.0.1
  provider: ^6.0.2
  qr_flutter: ^4.0.0
  responsive_framework: ^1.1.0
  shared_preferences: ^2.2.2
  theme_provider: ^0.6.0
  tinycolor2: ^3.0.1
  universal_html: ^2.0.8
  url_launcher: ^6.2.5
  web_socket_channel: ^2.4.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dependency_overrides:
  #win32: ^5.0.5
  #i18n_extension: ^11.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  intl_utils: ^2.8.2
  build_runner:
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic

  assets:
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/